### ISSUE TITLE
How do i fix this "Exception in thread "main" java.lang.ExceptionInInitializerError         at com.lnicf.PortMiner.PortMiner.main(PortMiner.java:59) Caused by: java.awt.HeadlessException: No X11 DISPLAY variable was set, but this program performed an operation which requires it.         at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)         at java.awt.Window.<init>(Window.java:536)         at java.awt.Frame.<init>(Frame.java:420)         at javax.swing.JFrame.<init>(JFrame.java:233)         at com.lnicf.PortMiner.Progress.<clinit>(Progress.java:14)         ... 1 more"

### ISSUE THREAD

**Issue by Neutrideo** [smithy212000/PortMiner#5]

**Comment by smithy212000** [comment]
Not a problem with PortMiner, looks like you're running PortMiner without having a display connected (possibly because you're using SSH?). Judging by your last issue I'd guess you're using this on a Raspberry Pi, and PortMiner has an interface that requires a display. Try using the PortMiner plugin instead as this will work from the command line.

**Comment by Neutrideo** [comment]
I use it in vnc connectivity

**Comment by smithy212000** [comment]
That'd be why it's not working. You'll either have to connect a display
directly or use the plugin for it to work on command line

**Comment by Neutrideo** [comment]
Is there a script which can run it thriugh command line?

**Comment by smithy212000** [comment]
There isn't, all you can do is either connect a display or use the plugin that you can find on the wiki
